site_name: FAQ Infrastrukturf√∂rderprogramm
site_url: https://ifpstz.github.io/ifp-faq/
theme:
  name: material
  language: de

  # Navigation
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - content.code.copy

  # Heller & dunkler Modus
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Dunkelmodus aktivieren
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: hellen Modus aktivieren

  # Schriftarten auf Berlin Type umstellen
  font:
    text: "Berlin Type"
    code: "Fira Code"

nav:
  - Startseite: index.md
  - Blog: blog/index.md

extra_css:
  - styles/Berlin.css
extra_templates:
  - admin/index.html
  - admin/config.yml

plugins:
  - search
  - blog
